include: package:flutter_lints/flutter.yaml
analyzer:
  plugins:
    riverpod_lint: 3.1.0
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
linter:
  rules:
    # Style
    #prefer_single_quotes: true
    #always_use_package_imports: true
    #avoid_print: true
    #prefer_const_constructors: true
    #prefer_const_declarations: true
    #prefer_final_locals: true

    # Safety
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true

custom_lint:
  rules:
    - riverpod_final_provider: true
    - scoped_providers_should_specify_dependencies: true